import Layout from "@/components/Layout";
import Head from "next/head";
import Image from "next/image";
import welcome from '../../public/images/svgs/welcome.svg'
import AnimatedText from "@/components/AnimatedText";
import InputField from "@/components/input";
import NavBar from "@/components/NavBar";
import Link from "next/link";
import { useEffect, useState } from "react";
import { useRouter } from "next/router";
import axios from "axios";
import { APIKey, BaseURL } from "@/constant/baseURL";

const login = () => {
    const [username, setUsername] = useState('');
    const [password, setPassword] = useState('');
    const [loggedInUser, setLoggedInUser] = useState(null);
    const router = useRouter()

    useEffect(() => {
        const user = localStorage.getItem("user")
        if (user == undefined || user == null) {

        }
    }, [])
    

    const handleLogin = async (e) => {
        e.preventDefault();
        //Logika autentikasi disini

        try {
            axios({
                method: 'get',
                url: `${BaseURL}/users?select=*&username=eq.${username}`,
                headers:{
                    "Content-Type": "application/json",
                    Authorization: `Bearer ${APIKey}`,
                    apikey: APIKey
                },
            })
                .then(function (response) {
                    console.log(response)
                    const userPassword=response.data[0].password
                    if (userPassword == password) {
                        delete response.data[0]['password']
                        let user = JSON.stringify(response.data[0])
                        localStorage.setItem("user", user)
                        return router.push('/')
                    }
                    alert("Gagal Login!")
                });
        } catch {
            console.error("Gagal login")
            alert("Internal server error!")
        }
    };
    return (
        <>
            <Head>
            <title>PeduliHijau | Log In</title>
            <meta name="description" content="Generated by create next app" />
            </Head>
            <main className='flex items-center text-dark w-full min-h-screen'>
                <Layout className='py-24'>
                    <div className='flex items-center justify-between w-full'>
                        <div className='w-2/5'>
                        <Image src={welcome} alt="Welcome" className='w-full h-auto' />
                        </div>
                        <div className='w-1/2 flex flex-col item-center self-center px-16'>
                        <AnimatedText text="Masuk" className='!text-4xl !text-left'/>
                        <form onSubmit={handleLogin} className='space-y-4 w-full'>
                            <InputField
                                label="Username"
                                type="text"
                                name="username"
                                value={username}
                                onChange={(e) => setUsername(e.target.value)}
                                placeholder="Masukkan username kamu"
                            />
                            <InputField
                                label="Kata Sandi"
                                type="password"
                                name="Kata Sandi"
                                value={password}
                                onChange={(e) => setPassword(e.target.value)}
                                placeholder="Masukkan kata sandi kamu"
                            />

                            <div className='flex items-center justify-center mt-2'>
                                <button
                                onClick={handleLogin}
                                style={{width: "100%"}}
                                className="flex items-center justify-center bg-primary text-light p-2.5 px-6
                                rounded-lg text-base font-semibold hover:bg-light hover:text-primary
                                border border-solid border-transparent hover:border-primary"
                                >Masuk
                                </button>
                            </div>
                        </form>
                        <p className='my-4 text-base font-medium'>
                            Belum punya akun?{' '}
                            <Link className='text-primary text-bold hover:underline' href='/register'>
                            Daftar
                            </Link>
                        </p>
                        </div>
                    </div>
                </Layout>
            </main>
        </>
    )
}

login.hideNavAndFooter = true;

export default login