import Layout from "@/components/Layout";
import Head from "next/head";
import Image from "next/image";
import welcome from '../../public/images/svgs/welcome.svg'
import AnimatedText from "@/components/AnimatedText";
import InputField from "@/components/input";
import Link from "next/link";
import { useState } from "react";

import { useRouter } from "next/router";
import axios from "axios";
import { APIKey, BaseURL } from "@/constant/baseURL";

const register = () => {
    const [username, setUsername] = useState('');
    const [name, setName] = useState('');
    const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');
    const [birthDate, setBirthDate] = useState('');

    const handleRegister = async (e) => {
        e.preventDefault();
        // Logika registrasi di sini

        try {
            axios({
                method: 'post',
                url: `${BaseURL}/users`,
                headers:{
                    "Content-Type": "application/json",
                    Authorization: `Bearer ${APIKey}`,
                    apikey: APIKey
                },
                data: {"username": username, 
                    "name": name, 
                    "password": password,
                    "birth_date": birthDate,
                    "email": email
                }
                
            })
                .then(function (response) {
                    console.log(response)
                });
        } catch {
            console.error("Gagal register")
        }
        
    };

    return (
        <>
            <Head>
            <title>PeduliHijau | Daftar</title>
            <meta name="description" content="Generated by create next app" />
            </Head>
            <main className='flex items-center text-dark w-full min-h-screen'>
                <Layout className='py-24'>
                    <div className='flex items-center justify-between w-full'>
                        <div className='w-2/5'>
                        <Image src={welcome} alt="Welcome" className='w-full h-auto' />
                        </div>
                        <div className='w-1/2 flex flex-col item-center self-center px-16'>
                        <AnimatedText text="Daftar" className='!text-4xl !text-left'/>
                        <form onSubmit={handleRegister} className='space-y-2'>
                            <InputField
                                label="Nama"
                                type="text"
                                name="name"
                                value={name}
                                onChange={(e) => setName(e.target.value)}
                                placeholder="Masukkan nama kamu"
                            />
                            <InputField
                                label="Username"
                                type="text"
                                name="username"
                                value={username}
                                onChange={(e) => setUsername(e.target.value)}
                                placeholder="Masukkan username kamu"
                            />
                            <InputField
                                label="Email"
                                type="email"
                                name="email"
                                value={email}
                                onChange={(e) => setEmail(e.target.value)}
                                placeholder="Masukkan email kamu"
                            />
                            <InputField
                                label="Tanggal Lahir"
                                type="date"
                                name="birthdate"
                                value={birthDate}
                                onChange={(e) => setBirthDate(e.target.value)}
                                placeholder="Masukkan tanggal lahir kamu"
                            />
                            <InputField
                                label="Kata Sandi"
                                type="password"
                                name="Kata Sandi"
                                value={password}
                                onChange={(e) => setPassword(e.target.value)}
                                placeholder="Masukkan kata sandi kamu"
                            />
                            <div className='flex items-center justify-center mt-2'>
                                <button 
                                onClick={handleRegister}
                                style={{width: "100%"}}
                                className="flex items-center justify-center bg-primary text-light p-2.5 px-6
                                rounded-lg text-base font-semibold hover:bg-light hover:text-primary
                                border border-solid border-transparent hover:border-primary"
                                >Daftar
                                </button>
                            </div>
                        </form>
                        <p className='my-4 text-base font-medium'>
                            Sudah punya akun?{' '}
                            <Link className='text-primary text-bold hover:underline' href='/login'>
                            Masuk
                            </Link>
                        </p>
                        </div>
                    </div>
                </Layout>
            </main>
        </>
    );
};

register.hideNavAndFooter = true;

export default register;
